api_platform:
    # The title of the API.
    title: 'Notation API'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        force_eager: false
    collection:
        pagination:
            items_per_page: 30
            client_enabled: true
            enabled_parameter_name : pagination
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value